# Generated by Django 4.2.2 on 2023-06-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sara_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abt_carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='abt_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='writings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
