# Generated by Django 4.2.2 on 2023-06-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sara_website', '0002_abt_carousel_abt_description_writings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abt_carousel',
            name='name',
        ),
        migrations.AddField(
            model_name='abt_carousel',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
