# Generated by Django 4.2.2 on 2023-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sara_website', '0004_abt_description_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='paints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='paints')),
            ],
        ),
    ]
