# Generated by Django 4.2.2 on 2023-06-27 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sara_website', '0005_paints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paints',
            old_name='file',
            new_name='paint_img',
        ),
    ]
