# Generated by Django 4.2.2 on 2023-06-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sara_website', '0006_rename_file_paints_paint_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paints',
            name='paint_img',
            field=models.ImageField(blank=True, null=True, upload_to='paints'),
        ),
    ]
